# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI acceptance tests (more JDKs)

on:
  schedule:
    # run integration tests every Thursday
    - cron: "31 06 * * 4"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' && !contains(github.event.pull_request.labels.*.name, 'ci:full') }}
permissions:
  contents: read

jobs:
  build:
    runs-on: [ubuntu-latest]
    timeout-minutes: 15
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        jdk: ['17', '21', '22']
        distribution: ['temurin', 'corretto', 'zulu', 'liberica']
        experimental: [false]
        include:
          - jdk: '17'
            distribution: 'microsoft'
            experimental: false
          - jdk: '17'
            distribution: 'adopt-openj9'
            experimental: false
          - jdk: '23'
            distribution: 'zulu'
            experimental: true
          - jdk: '24-ea'
            distribution: 'zulu'
            experimental: true

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@8df1039502a15bceb9433410b1a100fbe190c53b # v4.5.0
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.jdk }}
      - uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-${{ matrix.jdk }}_${{ matrix.distribution }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.jdk }}_${{ matrix.distribution }}-maven-
      - name: Build with Maven
        run: mvn -B -Pacceptance verify --file src/pom.xml
      - name: Allow failures
        run: 'true'
