name: Rebase
on:
  schedule:
    - cron:  '40 7 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  rebase:
    permissions:
      contents: write  # for peter-evans/rebase to push code to rebase
      pull-requests: read  # for peter-evans/rebase to get info about PRs
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          egress-policy: audit

      - uses: peter-evans/rebase@87c3fd9344792e51ab1c7494c3369620c84ed852 # v3.1.0
        with:
          exclude-labels: |
            no-rebase
            dependencies
          # exclude-drafts: true
